version: '3.7'

services:
  coworking_db:
    hostname: db
    image: postgres:16
    container_name: coworking_db
    ports:
      - "5432:5432"
    env_file:
      - .env

  coworking_redis:
    image: redis:7
    container_name: coworking_redis
    command: --port 6379
    expose:
      - 6379

  backend:
    build:
      context: ./backend
    env_file:
      - .env
    container_name: coworking_app
    command: [ "/docker/app.sh" ]
    ports:
      - "8000:8000"
    depends_on:
      - coworking_db
      - coworking_redis

#  frontend:
#    build:
#      context: ./frontend/coworking
#    ports:
#      - "3000:3000"