version: '3.7'

services:
  coworking_db:
    hostname: coworking_db
    image: postgres:16
    container_name: coworking_db
    ports:
      - "5437:5432"
    env_file:
      - .env

  backend:
    build:
      context: ./backend
    env_file:
      - .env
    container_name: coworking_app
    command: [ "/docker/app.sh" ]
    ports:
      - "8000:8000"
    depends_on:
      - coworking_db

#  frontend:
#    build:
#      context: ./frontend/coworking
#    ports:
#      - "3000:3000"