"""upload files

Revision ID: 268b74d31ed6
Revises: f9e555baf81f
Create Date: 2024-07-19 13:41:19.633998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '268b74d31ed6'
down_revision: Union[str, None] = 'f9e555baf81f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('image', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'image')
    # ### end Alembic commands ###
