"""group

Revision ID: 73d6dd29d56c
Revises: 3cb4c2e1e027
Create Date: 2024-06-24 19:22:32.549197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73d6dd29d56c'
down_revision: Union[str, None] = '3cb4c2e1e027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('members', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.add_column('note', sa.Column('owner', sa.String(), nullable=False))
    op.alter_column('note', 'deadline',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               existing_nullable=False)
    op.add_column('user', sa.Column('group', sa.String(), server_default='null', nullable=True))
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'group')
    op.alter_column('note', 'deadline',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('note', 'owner')
    op.drop_table('group')
    # ### end Alembic commands ###
