"""files project

Revision ID: 88a29937d9b8
Revises: 268b74d31ed6
Create Date: 2024-07-23 13:15:42.893688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88a29937d9b8'
down_revision: Union[str, None] = '268b74d31ed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('files', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'files')
    # ### end Alembic commands ###
