name: Parse School News

on:
  schedule:
    # Запуск каждые 5 минут
    - cron: '*/5 * * * *'
  workflow_dispatch: # Позволяет запускать workflow вручную

jobs:
  parse-and-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run parser
      run: python backend/src/parser.py

    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'

    - name: Commit and push if changed
      run: |
        git add backend/src/output.html
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          timestamp=$(date '+%Y-%m-%d %H:%M:%S')
          git commit -m "Update school news: ${timestamp} MSK"
          git push
        fi 